In [1]:
import numpy as np
import pandas as pd

from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sharmajicoder/genn-z-college-admission-dataset")

print("Path to dataset files:", path)

c:\Users\ankit\OneDrive\Desktop\Machine Learning\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\ankit\.cache\kagglehub\datasets\sharmajicoder\genn-z-college-admission-dataset\versions\1

In [3]:
df = pd.read_csv(f'{path}/genz_college_admission_prediction.csv')
df.head()

,student_id,age,gender,state,family_income,high_school_gpa,sat_score,act_score,attendance_rate,ap_courses,extracurricular_count,volunteer_hours,leadership_positions,coding_projects,social_media_hours,online_certifications,essay_score,recommendation_score,interview_score,admission_status
0,1,22,Male,Ohio,32560,3.20,734,27,91.0,3,3,85,1,4,4.8,1,96.3,90.5,71.7,1
1,2,19,Male,Virginia,39084,4.00,988,26,100.0,0,5,103,1,4,2.7,2,59.9,55.2,93.0,1
2,3,20,Male,Ohio,21615,2.90,1600,28,97.7,2,3,78,2,1,5.4,4,75.2,70.3,70.0,1
3,4,22,Male,Illinois,109493,3.86,1302,28,91.6,4,3,98,0,2,1.8,2,80.7,81.9,98.7,1
4,5,18,Male,Florida,50314,2.50,1342,30,91.8,3,4,35,1,2,5.8,3,63.1,73.7,67.5,1

In [4]:
df.shape

(1000000, 20)

In [5]:
df.columns

Index(['student_id', 'age', 'gender', 'state', 'family_income',
       'high_school_gpa', 'sat_score', 'act_score', 'attendance_rate',
       'ap_courses', 'extracurricular_count', 'volunteer_hours',
       'leadership_positions', 'coding_projects', 'social_media_hours',
       'online_certifications', 'essay_score', 'recommendation_score',
       'interview_score', 'admission_status'],
      dtype='str')

In [6]:
df.head()

,student_id,age,gender,state,family_income,high_school_gpa,sat_score,act_score,attendance_rate,ap_courses,extracurricular_count,volunteer_hours,leadership_positions,coding_projects,social_media_hours,online_certifications,essay_score,recommendation_score,interview_score,admission_status
0,1,22,Male,Ohio,32560,3.20,734,27,91.0,3,3,85,1,4,4.8,1,96.3,90.5,71.7,1
1,2,19,Male,Virginia,39084,4.00,988,26,100.0,0,5,103,1,4,2.7,2,59.9,55.2,93.0,1
2,3,20,Male,Ohio,21615,2.90,1600,28,97.7,2,3,78,2,1,5.4,4,75.2,70.3,70.0,1
3,4,22,Male,Illinois,109493,3.86,1302,28,91.6,4,3,98,0,2,1.8,2,80.7,81.9,98.7,1
4,5,18,Male,Florida,50314,2.50,1342,30,91.8,3,4,35,1,2,5.8,3,63.1,73.7,67.5,1

In [7]:
df = df.drop(columns='student_id')

In [8]:
df.head()

,age,gender,state,family_income,high_school_gpa,sat_score,act_score,attendance_rate,ap_courses,extracurricular_count,volunteer_hours,leadership_positions,coding_projects,social_media_hours,online_certifications,essay_score,recommendation_score,interview_score,admission_status
0,22,Male,Ohio,32560,3.20,734,27,91.0,3,3,85,1,4,4.8,1,96.3,90.5,71.7,1
1,19,Male,Virginia,39084,4.00,988,26,100.0,0,5,103,1,4,2.7,2,59.9,55.2,93.0,1
2,20,Male,Ohio,21615,2.90,1600,28,97.7,2,3,78,2,1,5.4,4,75.2,70.3,70.0,1
3,22,Male,Illinois,109493,3.86,1302,28,91.6,4,3,98,0,2,1.8,2,80.7,81.9,98.7,1
4,18,Male,Florida,50314,2.50,1342,30,91.8,3,4,35,1,2,5.8,3,63.1,73.7,67.5,1

In [9]:
df.dtypes

age                        int64
gender                       str
state                        str
family_income              int64
high_school_gpa          float64
sat_score                  int64
act_score                  int64
attendance_rate          float64
ap_courses                 int64
extracurricular_count      int64
volunteer_hours            int64
leadership_positions       int64
coding_projects            int64
social_media_hours       float64
online_certifications      int64
essay_score              float64
recommendation_score     float64
interview_score          float64
admission_status           int64
dtype: object

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.head()

,age,gender,state,family_income,high_school_gpa,sat_score,act_score,attendance_rate,ap_courses,extracurricular_count,volunteer_hours,leadership_positions,coding_projects,social_media_hours,online_certifications,essay_score,recommendation_score,interview_score,admission_status
0,22,Male,Ohio,32560,3.20,734,27,91.0,3,3,85,1,4,4.8,1,96.3,90.5,71.7,1
1,19,Male,Virginia,39084,4.00,988,26,100.0,0,5,103,1,4,2.7,2,59.9,55.2,93.0,1
2,20,Male,Ohio,21615,2.90,1600,28,97.7,2,3,78,2,1,5.4,4,75.2,70.3,70.0,1
3,22,Male,Illinois,109493,3.86,1302,28,91.6,4,3,98,0,2,1.8,2,80.7,81.9,98.7,1
4,18,Male,Florida,50314,2.50,1342,30,91.8,3,4,35,1,2,5.8,3,63.1,73.7,67.5,1

In [12]:
obj = LabelEncoder()
df['gender']= obj.fit_transform(df['gender'])
df['state']= obj.fit_transform(df['state'])

In [13]:
df.dtypes

age                        int64
gender                     int64
state                      int64
family_income              int64
high_school_gpa          float64
sat_score                  int64
act_score                  int64
attendance_rate          float64
ap_courses                 int64
extracurricular_count      int64
volunteer_hours            int64
leadership_positions       int64
coding_projects            int64
social_media_hours       float64
online_certifications      int64
essay_score              float64
recommendation_score     float64
interview_score          float64
admission_status           int64
dtype: object

In [14]:
df.columns

Index(['age', 'gender', 'state', 'family_income', 'high_school_gpa',
       'sat_score', 'act_score', 'attendance_rate', 'ap_courses',
       'extracurricular_count', 'volunteer_hours', 'leadership_positions',
       'coding_projects', 'social_media_hours', 'online_certifications',
       'essay_score', 'recommendation_score', 'interview_score',
       'admission_status'],
      dtype='str')

In [15]:
x =df[['age', 'gender', 'state', 'family_income', 'high_school_gpa',
       'sat_score', 'act_score', 'attendance_rate', 'ap_courses',
       'extracurricular_count', 'volunteer_hours', 'leadership_positions',
       'coding_projects', 'social_media_hours', 'online_certifications',
       'essay_score', 'recommendation_score', 'interview_score']]

y =df['admission_status']

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [ ]:
model = AdaBoostClassifier()
model.fit(x_train,y_train)

In [ ]:
predict = model.predict(x_test)
predict

array([1, 1, 1, ..., 1, 1, 1], shape=(200000,))

In [ ]:
from sklearn.metrics import accuracy_score

score = accuracy_score(y_test, predict)

print('Accuracy', score)

Accuracy 0.89245